### ISSUE TITLE
End-of-File convention in CodeIgniter has been changed

### ISSUE THREAD

**Issue by ivantcholakov** [bcit-ci/codeigniter3-translations#144]
See https://github.com/bcit-ci/CodeIgniter/pull/3490

* At the ends of files the closing blocks that look like:

```php
/* End of file autoload.php */
/* Location: ./application/config/autoload.php */
```

are removed.

* Files end with an empty line.
This makes possible the GitHubb editor to be used too for minor quick changes within sources.

----------------------------------

@jim-parry  My question is, should this change be applied within this project too?

**Comment by Razican** [comment]
I think it should. This is part of the project.

**Comment by jim-parry** [comment]
I have no problem with this suggestion .. the closing comments have been a pain and don't add to clarity, IMHO.

**Comment by michalsn** [comment]
I think we can close this issue, because all the files have been updated.
