### ISSUE TITLE
Opening Comment Blocks

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter3-translations#146]
There has been much discussion in the core repo about the opening license/comment blocks in our source code files. It makes sense that they remain, inside core framework files, i.e. those that are meant to end up inside system/.

I don't see them as *necessary* inside application/ files, but we want to make sure here that any contributed translations are freely usable by anyone who downloads this translations repo.

For the translations, I am comfortable removing the block at the beginning of each _lang.php file, but replacing it with a license.txt file in the same folder as an idiom's folder. This preserves the intent while reducing the clutter.

Comments?

**Comment by ivantcholakov** [comment]
I don't see a problem.

**Comment by Razican** [comment]
I think it's the logical approach: license file in the root of each language, and a @license tag in each file.

**Comment by peterdenk** [comment]
Makes perfect sense!
Just make the change the way you prefer it in one of the languages so we can use that as a template.

**Comment by jim-parry** [comment]
The following makes the most sense to me as a simplified comment block header for a translation source file:

/**
 * System messages translation for CodeIgniter(tm) 
 * @author	CodeIgniter community
 * @copyright	Copyright (c) 2014 - 2015, British Columbia Institute of Technology (http://bcit.ca/)
 * @license	http://opensource.org/licenses/MIT	MIT License
 * @link	http://codeigniter.com
*/

If a contributor wants their name recognized, I would add it to the @author line.
If a contributor intends to defend their copyright, I would add an additional @copyright line (thinking here of Pieter Krul with Dutch).

It has to be clear that a translation can be freely used, and who will defend it.

Does this work for all?

**Comment by Razican** [comment]
It works for me

**Comment by jim-parry** [comment]
This is looking a lot cleaner :)

**Comment by jim-parry** [comment]
By the way ...
Someone pointed out that "(tm)" is pointless. They are sort of correct ... it should really be "(R)", as CodeIgniter is a registered trademark and not just a claimed trademark. I think it is sufficient for now, and don't propose to change it unless our lawyers get excited :-/
