### ISSUE TITLE
Missed new translation line

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter3-translations#195]
The following translations are missing the translated text for $lang['form_validation_in_list'], which was added recently.

@tsukasa japanese
@MSDehghan persian
@karidoe thai
@obozdag turkish
@Rufnex german

It would be great if you could tend to this, so I don't have to resort to Google translate

**Comment by Ruplahlava** [comment]
I will do it tomorrow, ok?

**Comment by yhoiseth** [comment]
Thanks for the heads-up. I've created a pull request.

On Sat, Mar 7, 2015 at 12:44 AM, Instructor, Computer Systems Technology <
notifications@github.com> wrote:

> The following translations are missing the translated text for
> $lang['form_validation_in_list'], which was added recently.
>
> @ster <https://github.com/ster> italian
> @tsukaka japanese
> @yhoiseth <https://github.com/yhoiseth> norwegian
> @MSDehghan <https://github.com/MSDehghan> persian
> @denghongcai <https://github.com/denghongcai> simplified-chinese
> @karidoe <https://github.com/karidoe> thai
> @PeterDaveHello <https://github.com/PeterDaveHello> traditional-chinese
> @obozdag <https://github.com/obozdag> turkish
> @Ruplahlava <https://github.com/Ruplahlava> czech
> @Rufnex <https://github.com/Rufnex> german
>
> It would be great if you could tend to this, so I don't have to resort to
> Google translate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcit-ci/codeigniter3-translations/issues/195>.
>



-- 
Yngve

**Comment by PeterDaveHello** [comment]
Traditional-Chinese was translated in PR #203 by @appleboy :+1:

**Comment by jim-parry** [comment]
Sorry about that, @PeterDaveHello  ... I will update the readme :)

**Comment by PeterDaveHello** [comment]
no mind
