### ISSUE TITLE
Simplified Chinese & UTF-8

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter3-translations#196]
I cannot properly open some of the simplified Chinese translation files inside NetBeans ... it complains about UTF-8 compatibility and many of the characters appear as question marks on a sort of stop sign background. Is this a problem generally? Is there a workaround?

Thanks

**Comment by denghongcai** [comment]
It's a encoding problem, I will figure it out and fire a pull request.

**Comment by jim-parry** [comment]
Cool, thank you!
