### ISSUE TITLE
Release prep

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter3-translations#220]
Some translations have been proposed, but no pull request received yet.
We are getting ready to finalize version 3, and missing translations will be removed from the list in the README.

@muzikant Slovak?
@ngangchill Bangla?

**Comment by karthik-code** [comment]
I (karthik-code) providing translations for Tamil not Thai. I'll complete
it today.

On 11 March 2015 at 22:28, Instructor, Computer Systems Technology <
notifications@github.com> wrote:

> Some translations have been proposed, but no pull request received yet.
> We are getting ready to finalize version 3, and missing translations will
> be removed from the list in the README.
>
> @muzikant <https://github.com/muzikant> Slovak?
> @karthik-code <https://github.com/karthik-code> Thai?
> @daif <https://github.com/daif> Arabic? your translation looks only
> partly completed. Is it appropriate for v3.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcit-ci/codeigniter3-translations/issues/220>.
>



-- 
*R. Karthikeyan*

“Don’t try to develop attitudes and philosophies. Why can’t you just be
here, without any specific attitude? Without any philosophy? Just aware.
Simply aware.” - SadhguruJV


Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.

**Comment by jim-parry** [comment]
Sorry, Karthik - you are correct :-/
Looking forward to it.

**Comment by karthik-code** [comment]
I have added the missing 2 messaged.

**Comment by sajid19991** [comment]
on to the gujarati now...willl fork and pull soon as possible...

**Comment by sajid19991** [comment]
is there a specific timeline which i need to keep in mind?

**Comment by jim-parry** [comment]
@sajid19991 I want to release the "official" translations at about the same time as the CI3 release. That gives us a window of about a week, barring unforseen issues with the CI3 RC3.

**Comment by sajid19991** [comment]
@jim-parry no worries, it will be ready before that, in fact its almost ready...

**Comment by sajid19991** [comment]
@jim-parry full language uploaded, pull request pending..

**Comment by codeonion** [comment]
I have completed Urdu translation. Will it be added in the CI3?

**Comment by jim-parry** [comment]
@codeonion The translations releases will be kept in sync with the framework itself. When CI3.0 is officially released, there will be a corresponding translations release, with all of the completed translations at that point, including yours :)
This means that Slovak ( @muzikant ), Bangla ( @ngangchill ) and Arabic ( @daif ) might not make it in.

**Comment by codeonion** [comment]
I see! so these are separate. That is wonderful! Thanks for clearing my understanding of that.

**Comment by daif** [comment]
@jim-parry Arabic language has been updated and it's ready for CI3.0
