### ISSUE TITLE
Wouldn't it be better to separate this project in repositories?

### ISSUE THREAD

**Issue by giovannipds** [bcit-ci/codeigniter3-translations#310]
Hi people. When I came here today to grab one translation, I was wondering, wouldn't it be better to separate every single translation in an specific repo? In a world like nowadays where we're using much of composer, bower, npm, it would be better to have the translations as separate dependencies, I think. That way we could simply install each of them like `composer install translation-x`, or even through a yeoman generator, like `yo generator-ci-translate en`.

What do you guys think about it? The best way I think, it would be having them integrated through composer. Any thoughts about that? Don't know if you've already discussed that somewhere...

Hope opening this issue is ok to discuss about it, if is not, just let me know...

Regards, Gio.

**Comment by jim-parry** [comment]
This was one of the two original suggestions - (1) separate repos for everything, or (2) one repo which held them all. The dicsussion was lengthy, and we started out with separate repos, but that got complicated and awkward to maintain, really quickly. I then consolidated all the translations into the one repo (this one).
I don't know how many of the users use just one of the translations, and how many use several of them to provide localization in their apps. That could be an interesting question, with a vote, on the forum.
In fact, I want to see this issue discussed on the forum, with the opportunity for the community to contribute to the debate and discussion, before considering breaking this repo into multiple ones, each of which I would be the maintainer for!

**Comment by giovannipds** [comment]
I agree! In fact, my opinion is to have the both forms, a way to get just one of the translations and a way to get them all. I personally just use one translation, and will use other just if needed in the future.

I have open this issue after using the [h5bp server configs](https://github.com/h5bp/server-configs), which in this repo have a link to the other repos. Using [the generator](https://github.com/h5bp/generator-server-configs), is very practical to get a server config by the community.

Can we continue this discussion in the forum and put it to vote, as you suggested?

Gio.
