### ISSUE TITLE
Translation line added to imglib_lang.php

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter3-translations#339]
A new translation item has been added to the imglib library translations:
$lang['imglib_invalid_image'] = 'The provided image is not valid.';

@tgrnmrdn @Qarakom @kabircse @Ignasimg @pkrul @Rufnex 
@xargr  @shindesushilkumar @tsukasa @Chanthoeun
@dgvirtual @KwonLatte @vadimyer @novakurosevic
@peterdenk  @karidoe @codeonion 

Once you update your translation, I will remove your handle from this list :)

**Comment by appleboy** [comment]
https://github.com/bcit-ci/codeigniter3-translations/pull/345 Done!

**Comment by sajid19991** [comment]
#349 Done!

**Comment by yhoiseth** [comment]
#352

**Comment by orionstar** [comment]
#358

**Comment by DavisMiculis** [comment]
Thanks for notifying! #361

**Comment by jim-parry** [comment]
Version 3.1.3 has been released, incorporating all the above changes. Any missing updates will be in the "develop" branch until the next release.

**Comment by xargr** [comment]
#366 done!
