### ISSUE TITLE
Missing Translators

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter3-translations#340]
Some of the translators' acocunts do not appear active anymore.
If I cannot find them, I will ask for new translation maintainers for these on the forum.

serbian                  3.1.0        @novakurosevic      Novak Urosevic ???
vietnamese               3.0.4        @tinhphaistc        Trần Xuân Sâm ???
japanese                 3.0.3        @tsukasa            Tsukasa Takao???

**Comment by rakheshthayyur** [comment]
please add folder for language malayalam

**Comment by jim-parry** [comment]
@rakheshthayyur If you wish to create a malayalam translation, please create a pull request for it :)

**Comment by jim-parry** [comment]
I have used Google translate for these.
